# Generated by Django 2.2.6 on 2019-10-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sender', models.IntegerField()),
                ('receiver', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('avatar', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('token', models.UUIDField(null=True)),
            ],
        ),
    ]
